# Copyright 2026 Firefly Software Solutions Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Structured Pydantic models for reasoning pattern outputs.

These models replace unstructured text parsing (magic stop-phrases,
newline splitting, regex extraction) with typed, validated schemas
that the LLM is instructed to produce as structured output.

Models are organised by purpose:

* **Thought / Action** -- shared across patterns that interleave
  reasoning and tool use.
* **Plan** -- structured plan with step definitions and status tracking.
* **Reflection** -- structured self-critique for reflexion patterns.
* **Branch evaluation** -- structured scoring for Tree of Thoughts.
* **Goal decomposition** -- structured phase/task breakdown.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Shared: Thought & Action
# ---------------------------------------------------------------------------


class ReasoningThought(BaseModel):
    """Structured thought produced by an LLM during reasoning.

    Replaces magic stop-phrases (``FINISH``, ``CONCLUSION:``) with an
    explicit ``is_final`` flag so that patterns can detect completion
    via schema rather than string matching.

    Attributes:
        content: The reasoning text.
        confidence: Optional self-assessed confidence (0.0–1.0).
        is_final: Whether this thought represents the final answer.
        final_answer: The final answer text when ``is_final`` is True.
    """

    content: str
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    is_final: bool = False
    final_answer: str | None = None


class ReasoningAction(BaseModel):
    """Structured action selection produced by the LLM.

    Attributes:
        tool_name: Name of the tool to invoke.
        tool_args: Arguments to pass to the tool.
        reasoning: Brief explanation of why this action was chosen.
    """

    tool_name: str
    tool_args: dict[str, Any] = Field(default_factory=dict)
    reasoning: str = ""


# ---------------------------------------------------------------------------
# Plan & Step definitions
# ---------------------------------------------------------------------------


class StepStatus(StrEnum):
    """Execution status of a plan step."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class PlanStepDef(BaseModel):
    """A single step within a structured plan.

    Attributes:
        id: Unique step identifier (e.g. ``"step_1"``).
        description: What this step accomplishes.
        dependencies: IDs of steps that must complete before this one.
        status: Current execution status.
        output: Result produced after execution (populated at runtime).
    """

    id: str
    description: str
    dependencies: list[str] = Field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    output: str | None = None


class ReasoningPlan(BaseModel):
    """Structured plan generated by plan-based reasoning patterns.

    Attributes:
        goal: The high-level goal this plan addresses.
        steps: Ordered list of step definitions.
    """

    goal: str
    steps: list[PlanStepDef] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Reflection
# ---------------------------------------------------------------------------


class ReflectionVerdict(BaseModel):
    """Structured self-critique produced during reflexion reasoning.

    Replaces magic ``SATISFIED`` phrases with an explicit boolean flag.

    Attributes:
        is_satisfactory: Whether the answer meets quality standards.
        issues: Specific problems identified in the answer.
        suggestions: Concrete suggestions for improvement.
    """

    is_satisfactory: bool
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Tree of Thoughts: Branch Evaluation
# ---------------------------------------------------------------------------


class BranchEvaluation(BaseModel):
    """Structured evaluation of a reasoning branch.

    Attributes:
        branch_id: Index of the branch being evaluated (0-based).
        score: Quality score between 0.0 and 1.0.
        reasoning: Explanation of the score.
    """

    branch_id: int
    score: float = Field(ge=0.0, le=1.0)
    reasoning: str = ""


# ---------------------------------------------------------------------------
# Tree of Thoughts: Branch List
# ---------------------------------------------------------------------------


class BranchList(BaseModel):
    """Structured list of reasoning branches for Tree of Thoughts.

    Replaces fragile ``'---'`` text splitting with a proper typed list
    so that branches are cleanly separated by the LLM via structured output.

    Attributes:
        branches: Distinct reasoning approaches or solutions.
    """

    branches: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Goal Decomposition
# ---------------------------------------------------------------------------


class GoalPhase(BaseModel):
    """A phase within a goal decomposition.

    Attributes:
        name: Short name for the phase.
        description: What this phase accomplishes.
        tasks: Concrete, actionable tasks within this phase.
    """

    name: str
    description: str = ""
    tasks: list[str] = Field(default_factory=list)


class GoalDecompositionResult(BaseModel):
    """Structured result of goal decomposition.

    Attributes:
        goal: The original high-level goal.
        phases: Ordered list of phases.
    """

    goal: str
    phases: list[GoalPhase] = Field(default_factory=list)
