"""Tests for the code generator that converts graph models to Python code."""

from __future__ import annotations

from fireflyframework_genai.studio.codegen.models import (
    GraphEdge,
    GraphModel,
    GraphNode,
    NodeType,
)

from fireflyframework_genai.studio.codegen.generator import generate_python


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _agent_node(
    node_id: str,
    label: str = "",
    model: str = "openai:gpt-4o",
    instructions: str = "",
    **extra_data: object,
) -> GraphNode:
    """Shortcut to build an agent GraphNode for tests."""
    data: dict = {"model": model, "instructions": instructions, **extra_data}
    return GraphNode(
        id=node_id,
        type=NodeType.AGENT,
        label=label or node_id,
        position={"x": 0.0, "y": 0.0},
        data=data,
    )


def _edge(source: str, target: str, edge_id: str | None = None) -> GraphEdge:
    """Shortcut to build a GraphEdge."""
    return GraphEdge(
        id=edge_id or f"{source}->{target}",
        source=source,
        target=target,
    )


def _compiles(code: str) -> bool:
    """Return True if *code* is syntactically valid Python."""
    try:
        compile(code, "<generated>", "exec")
        return True
    except SyntaxError:
        return False


# ---------------------------------------------------------------------------
# Single agent (standalone, no edges)
# ---------------------------------------------------------------------------


class TestSingleAgentStandalone:
    def test_single_agent_produces_standalone_definition(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("classifier", instructions="Classify the input text.")],
        )
        code = generate_python(graph)

        assert "FireflyAgent" in code
        assert "PipelineBuilder" not in code
        assert 'name="classifier"' in code
        assert 'model="openai:gpt-4o"' in code
        assert 'instructions="Classify the input text."' in code

    def test_single_agent_has_module_docstring(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("a", instructions="Do stuff.")],
        )
        code = generate_python(graph)

        assert code.startswith('"""Pipeline generated by Firefly Studio."""')

    def test_single_agent_has_future_annotations(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("a", instructions="Do stuff.")],
        )
        code = generate_python(graph)

        assert "from __future__ import annotations" in code

    def test_single_agent_compiles(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("classifier", instructions="Classify the input text.")],
        )
        code = generate_python(graph)

        assert _compiles(code)

    def test_variable_name_matches_node_id(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("summarizer", instructions="Summarize.")],
        )
        code = generate_python(graph)

        assert "summarizer = FireflyAgent(" in code


# ---------------------------------------------------------------------------
# Pipeline (edges present)
# ---------------------------------------------------------------------------


class TestPipelineGeneration:
    def test_two_agents_with_edge_generates_pipeline(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node("a", instructions="Agent A"),
                _agent_node("b", instructions="Agent B"),
            ],
            edges=[_edge("a", "b")],
        )
        code = generate_python(graph)

        assert "PipelineBuilder" in code
        assert "AgentStep" in code
        assert '.add_node("a"' in code
        assert '.add_node("b"' in code
        assert '.add_edge("a", "b")' in code
        assert ".build()" in code

    def test_pipeline_compiles(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node("a", instructions="Agent A"),
                _agent_node("b", instructions="Agent B"),
            ],
            edges=[_edge("a", "b")],
        )
        code = generate_python(graph)

        assert _compiles(code)

    def test_pipeline_imports_all_needed_symbols(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node("x", instructions="X"),
                _agent_node("y", instructions="Y"),
            ],
            edges=[_edge("x", "y")],
        )
        code = generate_python(graph)

        assert "from fireflyframework_genai.agents.base import FireflyAgent" in code
        assert "from fireflyframework_genai.pipeline.builder import PipelineBuilder" in code
        assert "from fireflyframework_genai.pipeline.steps import AgentStep" in code

    def test_multiple_edges(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node("a", instructions="Agent A"),
                _agent_node("b", instructions="Agent B"),
                _agent_node("c", instructions="Agent C"),
            ],
            edges=[
                _edge("a", "b"),
                _edge("b", "c"),
            ],
        )
        code = generate_python(graph)

        assert '.add_edge("a", "b")' in code
        assert '.add_edge("b", "c")' in code
        assert _compiles(code)

    def test_diamond_topology(self) -> None:
        """A -> B, A -> C, B -> D, C -> D."""
        graph = GraphModel(
            nodes=[
                _agent_node("a", instructions="Start"),
                _agent_node("b", instructions="Left"),
                _agent_node("c", instructions="Right"),
                _agent_node("d", instructions="Merge"),
            ],
            edges=[
                _edge("a", "b"),
                _edge("a", "c"),
                _edge("b", "d"),
                _edge("c", "d"),
            ],
        )
        code = generate_python(graph)

        assert '.add_edge("a", "b")' in code
        assert '.add_edge("a", "c")' in code
        assert '.add_edge("b", "d")' in code
        assert '.add_edge("c", "d")' in code
        assert _compiles(code)


# ---------------------------------------------------------------------------
# Special characters and edge cases
# ---------------------------------------------------------------------------


class TestSpecialCharacters:
    def test_instructions_with_double_quotes(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("q", instructions='Say "hello" to the user.')],
        )
        code = generate_python(graph)

        assert _compiles(code)
        assert "hello" in code

    def test_instructions_with_single_quotes(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("q", instructions="It's a test.")],
        )
        code = generate_python(graph)

        assert _compiles(code)
        assert "It" in code

    def test_instructions_with_newlines_use_triple_quotes(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node(
                    "multi",
                    instructions="Step 1: Read.\nStep 2: Think.\nStep 3: Answer.",
                ),
            ],
        )
        code = generate_python(graph)

        assert _compiles(code)
        # Multi-line instructions should use triple-quoted strings
        assert '"""' in code or "'''" in code

    def test_instructions_with_backslashes(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("bs", instructions="Use path C:\\Users\\test")],
        )
        code = generate_python(graph)

        assert _compiles(code)

    def test_instructions_with_triple_quotes(self) -> None:
        """Instructions that themselves contain triple-double-quotes."""
        graph = GraphModel(
            nodes=[_agent_node("tricky", instructions='She said """wow""".')],
        )
        code = generate_python(graph)

        assert _compiles(code)


# ---------------------------------------------------------------------------
# Agent with no instructions
# ---------------------------------------------------------------------------


class TestAgentNoInstructions:
    def test_agent_with_empty_instructions(self) -> None:
        graph = GraphModel(
            nodes=[_agent_node("bare", instructions="")],
        )
        code = generate_python(graph)

        assert _compiles(code)
        assert 'name="bare"' in code

    def test_agent_with_missing_instructions_key(self) -> None:
        """data dict has no 'instructions' key at all."""
        node = GraphNode(
            id="noinstr",
            type=NodeType.AGENT,
            label="No Instructions",
            position={"x": 0, "y": 0},
            data={"model": "openai:gpt-4o"},
        )
        graph = GraphModel(nodes=[node])
        code = generate_python(graph)

        assert _compiles(code)
        assert 'name="noinstr"' in code

    def test_agent_with_no_model_uses_default(self) -> None:
        """data dict has no 'model' key -- should still generate valid code."""
        node = GraphNode(
            id="nomodel",
            type=NodeType.AGENT,
            label="No Model",
            position={"x": 0, "y": 0},
            data={"instructions": "Do something."},
        )
        graph = GraphModel(nodes=[node])
        code = generate_python(graph)

        assert _compiles(code)
        assert 'name="nomodel"' in code


# ---------------------------------------------------------------------------
# Empty graph
# ---------------------------------------------------------------------------


class TestEmptyGraph:
    def test_empty_graph_produces_valid_code(self) -> None:
        graph = GraphModel()
        code = generate_python(graph)

        assert _compiles(code)
        assert '"""Pipeline generated by Firefly Studio."""' in code

    def test_empty_graph_has_future_annotations(self) -> None:
        graph = GraphModel()
        code = generate_python(graph)

        assert "from __future__ import annotations" in code


# ---------------------------------------------------------------------------
# Multiple standalone agents (no edges)
# ---------------------------------------------------------------------------


class TestMultipleStandaloneAgents:
    def test_two_agents_no_edges(self) -> None:
        graph = GraphModel(
            nodes=[
                _agent_node("a", instructions="Agent A"),
                _agent_node("b", instructions="Agent B"),
            ],
        )
        code = generate_python(graph)

        # No pipeline when there are no edges
        assert "PipelineBuilder" not in code
        assert "a = FireflyAgent(" in code
        assert "b = FireflyAgent(" in code
        assert _compiles(code)
